### PR TITLE
Removed version number badge

### LINKED ISSUE #263: Remove version badge from README
It complicates the version bumping process, is easy to forget, adds negligible value when it's remembered, and is actively unhelpful if forgotten.

### PR DESCRIPTION
**Pull request by yoyosamo**
Don't know if you actually wanted someone to fix #263, but it wasn't too hard so I thought I'd help ;)

### CODE REVIEW

**Comment by Isabello** [comment]
We don't make PRs to master branch.

**Review by toschdev — APPROVED** [review]

**Comment by yoyosamo** [comment]
Oops, of course!
Thank you :)

**Comment by willclarktech** [comment]
Thanks @yoyosamo! For reference, issue #263 is in the [v0.3.0 project](https://github.com/LiskHQ/lisky/projects/3#card-5008006) so the branch to base off would be `0.3.0`. We should probably update our [CONTRIBUTING](https://github.com/LiskHQ/lisky/blob/0.3.0/CONTRIBUTING.md) file to make this clear though.

**Comment by willclarktech** [comment]
Created an issue for this: #265

**Pull request merged**
