### PR TITLE
Update .npmignore - Closes #257

### LINKED ISSUE #257: Update .npmignore
We have several new files in the root directory that don't need to be included in the published package.

### PR DESCRIPTION
**Pull request by 183h**
Closes #257

### CODE REVIEW

**Comment by willclarktech** [comment]
@mpuk Looking good, could you take the Gruntfile out too please?

**Comment by mpuk** [comment]
@willclarktech Yes but it does not exist in branch `0.3.0`. So I am not sure how to properly do it. Maybe merge `master` on my local and delete it ?

**Comment by willclarktech** [comment]
@mpuk I just mean remove this line: https://github.com/LiskHQ/lisky/pull/274/files#diff-0fd4ef892d9d4990033701887c2f9bccL6

We removed the file in `0.3.0`, so there's no longer any point ignoring it.

**Comment by mpuk** [comment]
@willclought Ok. I though you wanted to remove that file :D

**Review by willclarktech — APPROVED** [review]
Brilliant, thanks!

**Pull request merged**
